helloworld

diff --git a/plugins/wlx/dirchart_qml_qt_crap/src/Makefile b/plugins/wlx/dirchart_qml_qt_crap/src/Makefile
--- a/plugins/wlx/dirchart_qml_qt_crap/src/Makefile
+++ b/plugins/wlx/dirchart_qml_qt_crap/src/Makefile
@@ -28,12 +28,13 @@ dist:
 		test -f ../$(plugdir)_qt5.$(plugtype) && test -f ../plugin_qt5.qml && \
 			echo -e "[plugininstall]\ndescription=$(plugdescr)\ntype=$(plugtype)\nfile=$(plugdir)_qt5.$(plugtype)\ndefaultdir=$(plugdir)" > ../pluginst.inf && \
 			tar --exclude=../src -h -cvzf '../../../dist/$(plugtype)_$(plugdir)_qt5_$(shell date +%y.%m.%d).tar.gz' ../pluginst.inf ../plugin_qt5.qml ../$(plugdir)_qt5.$(plugtype) $(plugfiles) && \
-			rm ../pluginst.inf || echo $(plugdir)_qt5.$(plugtype) >> ../../../dist/.missing.log
+			rm ../pluginst.inf || echo "$(plugdir)_qt5.$(plugtype) + plugin_qt5.qml" >> ../../../dist/.missing.log
 
-		test -f ../$(plugdir)_qt6.$(plugtype) && test -f ../plugin_qt6.qml && \
-			echo -e "[plugininstall]\ndescription=$(plugdescr)\ntype=$(plugtype)\nfile=$(plugdir)_qt6.$(plugtype)\ndefaultdir=$(plugdir)" > ../pluginst.inf && \
-			tar --exclude=../src -h -cvzf '../../../dist/$(plugtype)_$(plugdir)_qt6_$(shell date +%y.%m.%d).tar.gz' ../pluginst.inf ../plugin_qt6.qml ../$(plugdir)_qt6.$(plugtype) $(plugfiles) && \
-			rm ../pluginst.inf || echo $(plugdir)_qt6.$(plugtype) >> ../../../dist/.missing.log
+		#test -f ../$(plugdir)_qt6.$(plugtype) && test -f ../plugin_qt6.qml && \
+		#	echo -e "[plugininstall]\ndescription=$(plugdescr)\ntype=$(plugtype)\nfile=$(plugdir)_qt6.$(plugtype)\ndefaultdir=$(plugdir)" > ../pluginst.inf && \
+		#	tar --exclude=../src -h -cvzf '../../../dist/$(plugtype)_$(plugdir)_qt6_$(shell date +%y.%m.%d).tar.gz' ../pluginst.inf ../plugin_qt6.qml ../$(plugdir)_qt6.$(plugtype) $(plugfiles) && \
+		#	rm ../pluginst.inf || echo "$(plugdir)_qt6.$(plugtype) + plugin_qt6.qml" >> ../../../dist/.missing.log
+
 
 clean:
 		$(RM) $(wildcard ../*.$(plugtype))
