UPD by j2969719: mpv_alt.wlx: The libmpv name is now stored in libmpv.txt. Added an alternative for the GTK2 version.

diff --git a/plugins/wlx/mpv_alt/src/Makefile b/plugins/wlx/mpv_alt/src/Makefile
--- a/plugins/wlx/mpv_alt/src/Makefile
+++ b/plugins/wlx/mpv_alt/src/Makefile
@@ -7,6 +7,7 @@ libs :=
 includes := -I../../../sdk
 
 gtk2_libs := `pkg-config --cflags --libs gtk+-2.0`
+gtk2_drawing_area_libs := `pkg-config --cflags --libs gtk+-2.0`
 qt5_libs := `pkg-config --cflags --libs Qt5Widgets`
 qt6_libs := `pkg-config --cflags --libs Qt6Widgets Qt6Core Qt6Gui`
 
@@ -19,10 +20,13 @@ plugfiles := $(filter-out $(wildcard ../*.$(plugtype)), $(wildcard ../*))
 detectstring := (EXT=\"AVI\")|(EXT=\"MKV\")|(EXT=\"FLV\")|(EXT=\"MPG\")|(EXT=\"MPEG\")|(EXT=\"MP4\")|(EXT=\"3GP\")|(EXT=\"MP3\")|(EXT=\"OGG\")|(EXT=\"WMA\")|(EXT=\"BIK\")|(EXT=\"VOC\")|(EXT=\"WAV\")|(EXT=\"WEBM\")|(EXT=\"VOB\")|(EXT=\"ROQ\")|(EXT=\"IVF\")|(EXT=\"MOV\")|(EXT=\"FLAC\")|(EXT=\"WMV\")|(EXT=\"M4A\")|(EXT=\"AIF\")|(EXT=\"AIFF\")|(EXT=\"OPUS\")
 
 
-all: gtk2 qt5 qt6
+all: gtk2 gtk2_drawing_area qt5 qt6
 
 gtk2:
 		$(CC) $(CFLAGS) -o '../$(plugdir)_$@.$(plugtype)' plugin.c $(libs) $($@_libs) $(includes) -D'PLUGNAME="'$(plugdir)_$@.$(plugtype)'"' -D'DETECT_STRING="$(detectstring)"' -DGTKPLUG || echo '$(plugdir)_$@.$(plugtype)' >> ../../../dist/.build_fail.lst
+
+gtk2_drawing_area:
+		$(CC) $(CFLAGS) -o '../$(plugdir)_$@.$(plugtype)' plugin.c $(libs) $($@_libs) $(includes) -D'PLUGNAME="'$(plugdir)_$@.$(plugtype)'"' -D'DETECT_STRING="$(detectstring)"' -DGTKPLUG -DDRAWAREA || echo '$(plugdir)_$@.$(plugtype)' >> ../../../dist/.build_fail.lst
 
 qt5:
 		$(CXX) $(CXXFLAGS) -o '../$(plugdir)_$@.$(plugtype)' plugin.c $(libs) $($@_libs) $(includes) -D'PLUGNAME="'$(plugdir)_$@.$(plugtype)'"' -D'DETECT_STRING="$(detectstring)"' -D'PLUGTARGET="$@"' || echo '$(plugdir)_$@.$(plugtype)' >> ../../../dist/.build_fail.lst
@@ -36,6 +40,10 @@ dist:
 			tar --exclude=../src -h -cvzf '../../../dist/$(plugtype)_$(plugdir)_gtk2_$(shell date +%y.%m.%d).tar.gz' ../pluginst.inf '../$(plugdir)_gtk2.$(plugtype)' $(plugfiles) && \
 			rm ../pluginst.inf || echo $(plugdir)_gtk2.$(plugtype) >> ../../../dist/.missing.log
 
+		test -f '../$(plugdir)_gtk2_drawing_area.$(plugtype)' && \
+			echo -e "[plugininstall]\ndescription=$(plugdescr)\ntype=$(plugtype)\nfile=$(plugdir)_gtk2.$(plugtype)\ndefaultdir=$(plugdir)" > ../pluginst.inf && \
+			tar --exclude=../src -h -cvzf '../../../dist/$(plugtype)_$(plugdir)_gtk2_$(shell date +%y.%m.%d).tar.gz' ../pluginst.inf '../$(plugdir)_gtk2.$(plugtype)' $(plugfiles) && \
+			rm ../pluginst.inf || echo $(plugdir)_gtk2.$(plugtype) >> ../../../dist/.missing.log
 
 		test -f '../$(plugdir)_qt5.$(plugtype)' && \
 			echo -e "[plugininstall]\ndescription=$(plugdescr)\ntype=$(plugtype)\nfile=$(plugdir)_qt5.$(plugtype)\ndefaultdir=$(plugdir)" > ../pluginst.inf && \
