helloworld

diff --git a/plugins/wlx/syntax-highlighting_qt/src/Makefile b/plugins/wlx/syntax-highlighting_qt/src/Makefile
--- a/plugins/wlx/syntax-highlighting_qt/src/Makefile
+++ b/plugins/wlx/syntax-highlighting_qt/src/Makefile
@@ -5,6 +5,8 @@ libs :=
 includes := -I../../../sdk
 
 qt5_libs := `pkg-config --cflags --libs Qt5Widgets` -I/usr/include/KF5/KSyntaxHighlighting/ -I/usr/include/KF5/KSyntaxHighlighting/KSyntaxHighlighting/ -lKF5SyntaxHighlighting
+qt6_libs := `pkg-config --cflags --libs Qt5Widgets Qt6Core Qt6Gui` -I/usr/include/KF6/KSyntaxHighlighting/ -I/usr/include/KF6/KSyntaxHighlighting/KSyntaxHighlighting/ -lKF6SyntaxHighlighting
+
 
 plugdir := $(shell basename '$(realpath ..)')
 plugtype := $(shell basename '$(realpath ../..)')
@@ -20,11 +22,19 @@ all: qt5
 qt5:
 		$(CXX) $(CXXFLAGS) -o '../$(plugdir)_$@.$(plugtype)' plugin.cpp $(libs) $($@_libs) $(includes) -D'PLUGNAME="'$(plugdir)_$@.$(plugtype)'"' -D'DETECT_STRING="$(detectstring)"' -D'PLUGTARGET="$@"' || echo '$(plugdir)_$@.$(plugtype)' >> ../../../dist/.build_fail.lst
 
+qt6:
+		$(CXX) $(CXXFLAGS) -o '../$(plugdir)_$@.$(plugtype)' plugin.cpp $(libs) $($@_libs) $(includes) -D'PLUGNAME="'$(plugdir)_$@.$(plugtype)'"' -D'DETECT_STRING="$(detectstring)"' -D'PLUGTARGET="$@"' || echo '$(plugdir)_$@.$(plugtype)' >> ../../../dist/.build_fail.lst
+
 dist:
 		test -f '../$(plugdir)_qt5.$(plugtype)' && \
 			echo -e "[plugininstall]\ndescription=$(plugdescr)\ntype=$(plugtype)\nfile=$(plugdir)_qt5.$(plugtype)\ndefaultdir=$(plugdir)" > ../pluginst.inf && \
 			tar --exclude=../src -h -cvzf '../../../dist/$(plugtype)_$(plugdir)_qt5_$(shell date +%y.%m.%d).tar.gz' ../pluginst.inf '../$(plugdir)_qt5.$(plugtype)' $(plugfiles) && \
 			rm ../pluginst.inf || echo $(plugdir)_qt5.$(plugtype) >> ../../../dist/.missing.log
+
+		test -f '../$(plugdir)_qt6.$(plugtype)' && \
+			echo -e "[plugininstall]\ndescription=$(plugdescr)\ntype=$(plugtype)\nfile=$(plugdir)_qt6.$(plugtype)\ndefaultdir=$(plugdir)" > ../pluginst.inf && \
+			tar --exclude=../src -h -cvzf '../../../dist/$(plugtype)_$(plugdir)_qt6_$(shell date +%y.%m.%d).tar.gz' ../pluginst.inf '../$(plugdir)_qt6.$(plugtype)' $(plugfiles) && \
+			rm ../pluginst.inf || echo $(plugdir)_qt6.$(plugtype) >> ../../../dist/.missing.log
 
 clean:
 		$(RM) $(wildcard ../*.$(plugtype))
