helloworld

diff --git a/plugins/wlx/qtpdfview_qt/src/Makefile b/plugins/wlx/qtpdfview_qt/src/Makefile
--- a/plugins/wlx/qtpdfview_qt/src/Makefile
+++ b/plugins/wlx/qtpdfview_qt/src/Makefile
@@ -7,8 +7,8 @@ includes := -I../../../sdk
 qt5_libs := `pkg-config --cflags --libs Qt5PdfWidgets`
 qt6_libs := `pkg-config --cflags --libs Qt6PdfWidgets`
 
-plugdir := $(shell basename $(realpath ..))
-plugtype := $(shell basename $(realpath ../..))
+plugdir := $(shell basename '$(realpath ..)')
+plugtype := $(shell basename '$(realpath ../..)')
 plugname := $(plugdir).$(plugtype)
 plugdescr := `grep '$(plugtype)/$(plugdir))' ../../../../plugins.md -1 | tail -1 | sed 's/[[]//' | sed 's/[]][\(][^\)]\+.//' | sed 's/\s[\(].\+[\)]//'`
 plugfiles := $(filter-out $(wildcard ../*.$(plugtype)), $(wildcard ../*))
@@ -19,20 +19,20 @@ detectstring :=
 all: qt5 qt6
 
 qt5:
-		$(CXX) $(CXXFLAGS) -o ../$(plugdir)_$@.$(plugtype) plugin.cpp $(libs) $($@_libs) $(includes) -D'PLUGNAME="$(plugdir)_$@.$(plugtype)"' -D'DETECT_STRING="$(detectstring)"' -D'PLUGTARGET="$@"' || echo $(plugdir)_$@.$(plugtype) >> ../../../dist/.build_fail.lst
+		$(CXX) $(CXXFLAGS) -o '../$(plugdir)_$@.$(plugtype)' plugin.cpp $(libs) $($@_libs) $(includes) -D'PLUGNAME="'$(plugdir)_$@.$(plugtype)'"' -D'DETECT_STRING="$(detectstring)"' -D'PLUGTARGET="$@"' || echo '$(plugdir)_$@.$(plugtype)' >> ../../../dist/.build_fail.lst
 
 qt6:
-		$(CXX) $(CXXFLAGS) -o ../$(plugdir)_$@.$(plugtype) plugin.cpp $(libs) $($@_libs) $(includes) -D'PLUGNAME="$(plugdir)_$@.$(plugtype)"' -D'DETECT_STRING="$(detectstring)"' -D'PLUGTARGET="$@"' || echo $(plugdir)_$@.$(plugtype) >> ../../../dist/.build_fail.lst
+		$(CXX) $(CXXFLAGS) -o '../$(plugdir)_$@.$(plugtype)' plugin.cpp $(libs) $($@_libs) $(includes) -D'PLUGNAME="'$(plugdir)_$@.$(plugtype)'"' -D'DETECT_STRING="$(detectstring)"' -D'PLUGTARGET="$@"' || echo '$(plugdir)_$@.$(plugtype)' >> ../../../dist/.build_fail.lst
 
 dist:
-		test -f ../$(plugdir)_qt5.$(plugtype) && \
+		test -f '../$(plugdir)_qt5.$(plugtype)' && \
 			echo -e "[plugininstall]\ndescription=$(plugdescr)\ntype=$(plugtype)\nfile=$(plugdir)_qt5.$(plugtype)\ndefaultdir=$(plugdir)" > ../pluginst.inf && \
-			tar --exclude=../src -h -cvzf '../../../dist/$(plugtype)_$(plugdir)_qt5_$(shell date +%y.%m.%d).tar.gz' ../pluginst.inf ../$(plugdir)_qt5.$(plugtype) $(plugfiles) && \
+			tar --exclude=../src -h -cvzf '../../../dist/$(plugtype)_$(plugdir)_qt5_$(shell date +%y.%m.%d).tar.gz' ../pluginst.inf '../$(plugdir)_qt5.$(plugtype)' $(plugfiles) && \
 			rm ../pluginst.inf || echo $(plugdir)_qt5.$(plugtype) >> ../../../dist/.missing.log
 
-		test -f ../$(plugdir)_qt6.$(plugtype) && \
+		test -f '../$(plugdir)_qt6.$(plugtype)' && \
 			echo -e "[plugininstall]\ndescription=$(plugdescr)\ntype=$(plugtype)\nfile=$(plugdir)_qt6.$(plugtype)\ndefaultdir=$(plugdir)" > ../pluginst.inf && \
-			tar --exclude=../src -h -cvzf '../../../dist/$(plugtype)_$(plugdir)_qt6_$(shell date +%y.%m.%d).tar.gz' ../pluginst.inf ../$(plugdir)_qt6.$(plugtype) $(plugfiles) && \
+			tar --exclude=../src -h -cvzf '../../../dist/$(plugtype)_$(plugdir)_qt6_$(shell date +%y.%m.%d).tar.gz' ../pluginst.inf '../$(plugdir)_qt6.$(plugtype)' $(plugfiles) && \
 			rm ../pluginst.inf || echo $(plugdir)_qt6.$(plugtype) >> ../../../dist/.missing.log
 
 clean:
